In [3]:
[[123, 12, 123, 12, 33],[],[]]


[[123, 12, 123, 12, 33], [], []]

In [6]:
import numpy
n = numpy.arange(27)

In [9]:
type(n)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [11]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [13]:
type(m)

numpy.ndarray

In [15]:
import cv2

In [18]:
img = cv2.imread("smallgray.png", 0)

In [20]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
cv2.imwrite("newsmallgray.png", img)

True

In [24]:
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [25]:
ims = numpy.hstack([img, img])

In [26]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)